apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: us-central1-docker.pkg.dev/ford-629e9fe73e712fb23f0ebbec/carstore-repo/carstore-frontend:v1
  imagePullSecrets:
  - name: artifact-registry-secret
